<?php

return [
    [
        "name" => "Spaghetti Carbonara",
        "description" => "Classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.",
        "price" => 12.50,
        "cover_image" => '/img/dishes/spaghetti-carbonara.png',
        "ingredients" => "Spaghetti Pasta, Guanciale, Eggs, Pecorino Cheese, Salt, Black pepper",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Saltimbocca alla Romana",
        "description" => "Tender veal cutlets topped with prosciutto and sage, sautéed in white wine.",
        "price" => 15.00,
        "cover_image" => '/img/dishes/saltimbocca-alla-romana.png',
        "ingredients" => "Veal, Prosciutto, Fresh sage, White wine, Butter, Salt, Pepper",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Cacio e Pepe",
        "description" => "Simple and delicious pasta dish with a creamy cheese and black pepper sauce.",
        "price" => 11.00,
        "cover_image" => '/img/dishes/cacio-e-pepe.png',
        "ingredients" => "Spaghetti, Pecorino Romano cheese, Black pepper, Salt",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Supplì",
        "description" => "Fried rice balls filled with mozzarella cheese, a Roman street food classic.",
        "price" => 5.00,
        "cover_image" => '/img/dishes/suppli-al-telefono.png',
        "ingredients" => "Rice, Mozzarella, Tomato sauce, Bread crumbs, Eggs, Salt, Pepper",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Rigatoni alla Gricia",
        "description" => "A traditional Roman pasta dish with guanciale, Pecorino Romano cheese, and black pepper.",
        "price" => 13.00,
        "cover_image" => '/img/dishes/rigatoni-alla-gricia.png',
        "ingredients" => "Rigatoni, Guanciale, Pecorino Romano cheese, Black pepper, Salt",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Pizza Margherita",
        "description" => "Traditional pizza topped with tomato sauce, mozzarella cheese, and fresh basil.",
        "price" => 10.00,
        "cover_image" => '/img/dishes/margherita-pizza.png',
        "ingredients" => "Pizza Dough, Tomato Sauce, Mozzarella, Basil, Olive oil, Salt",
        "restaurant_id" => 2,
    ],
    [
        "name" => "Pizza Quattro Stagioni",
        "description" => "Pizza divided into four sections, each with different toppings: artichokes, ham, mushrooms, and olives.",
        "price" => 12.00,
        "cover_image" => '/img/dishes/quattro-stagioni.png',
        "ingredients" => "Pizza Dough, Tomato Sauce, Mozzarella, Artichokes, Ham, Mushrooms, Olives",
        "restaurant_id" => 2,
    ],
    [
        "name" => "Pizza Diavola",
        "description" => "Spicy pizza with tomato sauce, mozzarella, and spicy salami.",
        "price" => 11.50,
        "cover_image" => '/img/dishes/diavola.png',
        "ingredients" => "Pizza Dough, Tomato Sauce, Mozzarella, Spicy Salami, Olive oil",
        "restaurant_id" => 2,
    ],
    [
        "name" => "Pizza Capricciosa",
        "description" => "Pizza with tomato sauce, mozzarella, ham, mushrooms, artichokes, and olives.",
        "price" => 12.50,
        "cover_image" => '/img/dishes/capricciosa.png',
        "ingredients" => "Pizza Dough, Tomato Sauce, Mozzarella, Ham, Mushrooms, Artichokes, Olives",
        "restaurant_id" => 2,
    ],
    [
        "name" => "Pizza Prosciutto e Funghi",
        "description" => "Pizza with tomato sauce, mozzarella, ham, and mushrooms.",
        "price" => 11.00,
        "cover_image" => '/img/dishes/prosciutto-e-funghi.png',
        "ingredients" => "Pizza Dough, Tomato Sauce, Mozzarella, Ham, Mushrooms",
        "restaurant_id" => 2,
    ],
    [
        "name" => "Lasagna",
        "description" => "Layers of pasta, meat sauce, and cheese, baked to perfection.",
        "price" => 14.00,
        "cover_image" => '/img/dishes/lasagna.png',
        "ingredients" => "Lasagna noodles, Ground Beef, Tomato Sauce, Mozzarella, Ham, Parmesan Cheese, Olive Oil",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Risotto ai Funghi",
        "description" => "Creamy risotto with a mix of wild mushrooms and parmesan cheese.",
        "price" => 13.50,
        "cover_image" => '/img/dishes/risotto-ai-funghi.png',
        "ingredients" => "Rice, Fresh Mushrooms, Olive Oil, Onion, Butter, Vegetable Broth, White Wine, Black Pepper, Fresh Parsley",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Tiramisu",
        "description" => "Classic Italian dessert made with layers of coffee-soaked ladyfingers, mascarpone cheese, and cocoa.",
        "price" => 7.00,
        "cover_image" => '/img/dishes/tiramisu.png',
        "ingredients" => "Savoiardi Biscuits, Eggs, Mascarpone Cheese, Espresso Coffee, Cocoa Powder Topping",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Bruschetta",
        "description" => "Grilled bread topped with fresh tomatoes, garlic, and basil.",
        "price" => 6.50,
        "cover_image" => '/img/dishes/bruschetta.png',
        "ingredients" => "Sliced Bread, Fresh Tomatoes, Basil, Olive Oil, Mozzarella, Garlic",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Insalata Caprese",
        "description" => "Salad made with fresh tomatoes, mozzarella cheese, basil, and a drizzle of olive oil.",
        "price" => 8.00,
        "cover_image" => '/img/dishes/insalata-caprese.png',
        "ingredients" => "Fresh Tomatoes, Basil, Olive Oil, Mozzarella",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Osso Buco",
        "description" => "Braised veal shanks with vegetables, white wine, and broth.",
        "price" => 18.00,
        "cover_image" => '/img/dishes/osso-buco.png',
        "ingredients" => "Veal Shanks, Onion, White Wine, Butter, Black Pepper, Flour, Olive Oil, Meat Broth",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Fettuccine Alfredo",
        "description" => "Pasta in a rich and creamy parmesan sauce.",
        "price" => 11.00,
        "cover_image" => '/img/dishes/fettuccine-alfredo.png',
        "ingredients" => "Fettuccine Pasta, Butter, Parmesan Cheese",
        "restaurant_id" => 1,
    ],
    [
        "name" => "Panna Cotta",
        "description" => "Creamy dessert topped with caramel sauce.",
        "price" => 6.00,
        "cover_image" => '/img/dishes/panna-cotta.png',
        "ingredients" => "Fresh Cream, Vanilla, Sugar, Gelatine Sheets",
        "restaurant_id" => 1,
    ],
];
